### ISSUE TITLE
有问题想联系您

### ISSUE THREAD

**Issue by 1713735544** [weiyu666/Graduation_Design-Distributed_Web_Spider#1]
我希望可以模拟这个系统的运行，现在有一些问题想要问您，您可以给我一下您的联系方式吗，感激不尽！！！

**Comment by weiyu666** [comment]
可以你直说：
1、邮件chenweiyu233@gmail.com
2、你先在csdn上面联系也行 https://blog.csdn.net/chenweiyu11962 私聊加好友
为了个人隐私什么的我就不在这里公开我的QQ 微信 电话什么的啦 去那里说吧；
